### PR TITLE
E3d

### PR DESCRIPTION
**Pull request by philfifi**
This is the merge of the 2 previous pull request (fan-duct-work and hot-end-work).
It allows the E3D head to be used, and adapt the fan-duct accordingly so that it fits.
Here is the result:
e3d_fan_duct

Let me know what you think.

### CODE REVIEW

**Comment by nophead** [comment]
It's a good piece of work, thanks. I can't merge it at the moment for a couple of reasons. Firstly this repository has to match the kits I am selling and I don't want to change the fan duct shape when J-Head is selected. It conflicts massively with changes I made locally to make the Huxley version work and also add a Z probe.

**Comment by jem-tech** [comment]
Is there a slt for this fan duct been looking for one to work with the e3d hotend?

**Comment by philfifi** [comment]
Hello Chris,
If you prefer, I can propose another branch where the shape of the duct is unchanged. (at least for Jhead. It has to be thinner for e3d anyway). But that will not solve anything about the conflicts. Are you ready to share your local modifications ? In another branch in the meantime. I can have a look at the conflicts and check how to resolve them.

**Comment by philfifi** [comment]
@jem-tech I am not sure to understand your question. The branch I propose is a possible solution to have a fan duct that fits with an E3D head. At least in theory. I printed the duct and it seems to fit correctly. I will mount it completely on the printer this weekend (hopefully).

**Comment by nophead** [comment]
Yes I don't want anything to change when E3D is not selected. 

As for the conflicts I know if I merge your changes I will not be able to merge mine. I don't really understand git enough. I actually develop with a difference source control and just use git to publish.

**Comment by jem-tech** [comment]
@philippe luc     i am looking to print the fan duct you proposed for
the e3d head but dont know mush about open scad. i guess what i am
asking is where can i get the file STL for the duct so i can print it?

**Comment by jem-tech** [comment]
@philippe luc     i am looking to print the fan duct you proposed for
the e3d head but dont know much about open scad. i guess what i am
asking is where can i get the  STL file for the duct so i can print it?

**Comment by philfifi** [comment]
Indeed this pull request induce too much changes in the fan duct, that doesn't necessary worth. This new request: https://github.com/nophead/Mendel90/pull/57 replaces this one, hence closing it. Thanks

**Pull request closed without merging**
